<?php

/**
 * @file
 * The OE Theme Helper module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_page_attachments().
 */
function oe_theme_helper_page_attachments(array &$page) {
  // Add ECL 2.0 required meta tags.
  $meta_default = [
    'ie_legacy_support' => [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'X-UA-Compatible',
        'content' => 'IE=edge,chrome=1',
      ],
    ],
  ];
  foreach ($meta_default as $key => $value) {
    $page['#attached']['html_head'][] = [$value, $key];
  }

  // Load ECL component library assets for oe_theme and its subthemes.
  $active_theme = \Drupal::theme()->getActiveTheme();
  if ($active_theme->getName() === 'oe_theme' || array_key_exists('oe_theme', $active_theme->getBaseThemeExtensions())) {
    $component_library = theme_get_setting('component_library') ?? 'ec';
    $page['#attached']['library'][] = 'oe_theme/component_library_' . $component_library;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function oe_theme_helper_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (!isset($build['content_moderation_control'])) {
    return;
  }

  // Ensure that the content moderation control block will always
  // show at the top, above any other elements.
  $build['content_moderation_control']['#weight'] = -500;
}

/**
 * Implements hook_theme().
 */
function oe_theme_helper_theme($existing, $type, $theme, $path) {
  return [
    'oe_theme_helper_address_inline' => [
      'variables' => [
        'address' => NULL,
        'address_items' => [],
        'address_delimiter' => NULL,
      ],
    ],
    'oe_theme_helper_in_page_navigation' => [
      'render element' => 'element',
    ],
    'oe_theme_helper_in_page_navigation_item' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter() for Accordion item.
 */
function oe_theme_helper_field_widget_oe_paragraphs_variants_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] !== 'oe_accordion_item') {
    return;
  }
  // Hide icon field as it's not supported in ECL 2.
  if (isset($element['subform']['field_oe_icon'])) {
    $element['subform']['field_oe_icon']['#access'] = FALSE;
  }
}

/**
 * Prepares variables for in-page navigation.
 *
 * Default template: oe-theme-helper-in-page-navigation.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function template_preprocess_oe_theme_helper_in_page_navigation(array &$variables) {
  $element = $variables['element'];

  $variables['title'] = !empty($element['#title']) ? $element['#title'] : '';
  $variables['children'] = !empty($element['#children']) ? $element['#children'] : '';
  $variables['entity'] = !empty($element['#entity']) ? $element['#entity'] : '';
  $variables['links'] = !empty($element['#links']) ? $element['#links'] : '';
}

/**
 * Prepares variables for in-page navigation item.
 *
 * Default template: oe-theme-helper-in-page-navigation-item.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function template_preprocess_oe_theme_helper_in_page_navigation_item(array &$variables) {
  $element = $variables['element'];

  $variables['title'] = !empty($element['#title']) ? $element['#title'] : '';
  $variables['children'] = !empty($element['#children']) ? $element['#children'] : '';
  $variables['entity'] = !empty($element['#entity']) ? $element['#entity'] : '';
  $variables['title_attributes'] = !empty($element['#title_attributes']) ? $element['#title_attributes'] : '';
}

/**
 * Default theme suggestions for custom field groups.
 *
 * @param array $variables
 *   An array of variables passed to the theme hook.
 * @param string $hook
 *   Hook name.
 *
 * @return array
 *   Theme suggestions.
 */
function _oe_theme_helper_field_group_theme_suggestions(array $variables, string $hook): array {
  $element = $variables['element'];
  $suggestions = [];

  $name = !empty($element['#group_name']) ? $element['#group_name'] : NULL;
  $entity_type = !empty($element['#entity_type']) ? $element['#entity_type'] : NULL;
  $bundle = !empty($element['#bundle']) ? $element['#bundle'] : NULL;

  if (!empty($name)) {
    $suggestions[] = $hook . '__' . $name;

    if (!empty($entity_type)) {
      $suggestions[] = $hook . '__' . $entity_type . '__' . $name;
    }
  }

  if (!empty($entity_type) && !empty($bundle)) {
    $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle;

    if (!empty($name)) {
      $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle . '__' . $name;
    }
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_theme_helper_theme_suggestions_oe_theme_helper_in_page_navigation(array $variables) {
  return _oe_theme_helper_field_group_theme_suggestions($variables, 'oe_theme_helper_in_page_navigation');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_theme_helper_theme_suggestions_oe_theme_helper_in_page_navigation_item(array $variables) {
  return _oe_theme_helper_field_group_theme_suggestions($variables, 'oe_theme_helper_in_page_navigation_item');
}
