<?php

/**
 * @file
 * Module file used for theming the Organisation content type references.
 */

declare(strict_types = 1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\oe_content_entity_contact\Entity\ContactInterface;

/**
 * Implements template_preprocess_field().
 */
function oe_theme_content_organisation_reference_preprocess_field__node__oe_publication_contacts(array &$variables): void {
  _oe_theme_content_organisation_reference_display_organisation_contact($variables);
}

/**
 * Displays an organisation node as contact.
 *
 * This only works if the "oe_content_organisation_reference" is enabled and
 * correctly configured, check its README.md for more information.
 * If any of the referenced contacts is an organisation we need to first check
 * if that organisation has any contact details and prevent it from rendering
 * if it does not.
 *
 * @param array $variables
 *   Render array.
 */
function _oe_theme_content_organisation_reference_display_organisation_contact(array &$variables): void {
  if (empty($variables['items'])) {
    return;
  }

  foreach ($variables['items'] as &$item) {
    /** @var \Drupal\Core\Entity\ContentEntityInterface $contact */
    $contact = $item['content']['#oe_contact'];
    $cacheable_metadata  = CacheableMetadata::createFromRenderArray($item['content']);
    // If the contact is not an organisation we don't care.
    if ($contact->bundle() !== 'oe_organisation_reference') {
      continue;
    }
    $organisation = $contact->oe_node_reference->entity;
    if (!$organisation instanceof ContentEntityInterface) {
      // If by some chance an organisation is not linked we do not render
      // the contact.
      $item['content']['#access'] = FALSE;
      continue;
    }
    $cacheable_metadata->addCacheableDependency($organisation);

    $organisation_contact = $organisation->oe_organisation_contact->entity;
    if (!$organisation_contact instanceof ContactInterface) {
      // Do not render the contact if the organisation does not have contact
      // details of its own.
      $item['content']['#access'] = FALSE;
      $cacheable_metadata->applyTo($item);
      continue;
    }
    $cacheable_metadata->addCacheableDependency($organisation_contact);
    $cacheable_metadata->applyTo($item);
  }
}
