clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
  sparql:
    image: registry.fpfis.eu/openeuropa/triple-store-dev
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - DISPLAY=:99
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  npm-build:
    group: prepare
    image: registry.fpfis.eu/fpfis/node:12.21.0
    commands:
      - npm install --unsafe-perm
      - NODE_ENV=production npm run build

  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: post-prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      event:
        exclude: tag
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run drupal:site-install
    when:
      event:
        exclude: tag
      matrix:
        TYPE: behat

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
    when:
      event:
        exclude: tag
      matrix:
        COMPOSER_BOUNDARY: highest

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/phpunit --group $BATCH
    when:
      event:
        exclude: tag
      matrix:
        TYPE: phpunit

  behat:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/behat --strict
    when:
      event:
        exclude: tag
      matrix:
        TYPE: behat

  before-release:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-dev
    commands:
      - ./vendor/bin/run release:create-archive --tag=${DRONE_TAG}
    when:
      event:
        include: tag

  github-release:
    image: registry.fpfis.eu/drone-plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      event:
        include: tag
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  include:
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: behat }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: phpunit, BATCH: batch2 }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: phpunit, BATCH: batch3 }

    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: behat }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: phpunit, BATCH: batch1 }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: phpunit, BATCH: batch2 }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: phpunit, BATCH: batch3 }
