workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/php71-build:latest
    environment:
      - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

matrix:
  DRUPAL_VERSION:
    - 8.6.x

clone:
  git:
    image: plugins/git:next
    depth: 1
    tags: true

pipeline:
  npm-build:
    group: prepare
    image: node:9.5.0
    commands:
      - npm install --unsafe-perm
      - npm run build

  composer-install:
    group: prepare
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer require --dev webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install
      # Reset permission since installation runs as root. @todo Fix this.
      - chown -R 1000:1000 build/sites/default
      - chmod -R 777 /tmp

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat

  before-release:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run release:create-archive
    when:
      matrix:
        DRUPAL_VERSION: 8.6.x
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      matrix:
        DRUPAL_VERSION: 8.6.x
      event: tag
