<?php

/**
 * @file
 * Module file used for theming the Organisation content type.
 */

declare(strict_types = 1);

/**
 * Prepares variables for in-page navigation.
 *
 * Default template: oe-theme-helper-in-page-navigation.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function oe_theme_content_organisation_preprocess_oe_theme_helper_in_page_navigation__node__oe_organisation(array &$variables): void {
  _oe_theme_content_helper_prepare_oe_theme_helper_in_page_navigation_with_image($variables, 'oe_organisation_logo');
}
