<?php

/**
 * @file
 * Test module.
 */

declare(strict_types=1);

use Drupal\oe_theme\ValueObject\FileValueObject;
use Drupal\oe_theme\ValueObject\GalleryItemValueObject;

/**
 * Implements hook_preprocess_pattern_file().
 */
function oe_theme_patterns_render_test_preprocess_pattern_file(&$variables) {
  $variables['file'] = FileValueObject::fromArray($variables['file']);
}

/**
 * Implements hook_preprocess_pattern_file_translation().
 */
function oe_theme_patterns_render_test_preprocess_pattern_file_translation(&$variables) {
  $variables['file'] = FileValueObject::fromArray($variables['file']);

  if ($variables['translations']) {
    foreach ($variables['translations'] as $index => $translation) {
      $variables['translations'][$index] = FileValueObject::fromArray($translation);
    }
  }
}

/**
 * Implements hook_preprocess_pattern_file_teaser().
 */
function oe_theme_patterns_render_test_preprocess_pattern_file_teaser(&$variables) {
  $variables['file'] = FileValueObject::fromArray($variables['file']);

  foreach ($variables['translations'] as $index => $translation) {
    $translation['file'] = FileValueObject::fromArray($translation['file']);
    $variables['translations'][$index] = $translation;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_theme_patterns_render_test_preprocess_pattern_gallery(&$variables) {
  foreach ($variables['items'] as $index => $values) {
    $variables['items'][$index] = GalleryItemValueObject::fromArray($values);
  }
}
