<?php

/**
 * @file
 * Module file used for theming the Publication content type.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function oe_theme_content_publication_theme() {
  return [
    'oe_theme_content_publication_description' => [
      'variables' => [
        'body' => '',
        'image' => '',
      ],
    ],
    'oe_theme_content_publication_collections' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_publication_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Run only for "Publication" content type.
  if ($entity->bundle() !== 'oe_publication') {
    return;
  }

  // Override field labels.
  if ($build['#view_mode'] === 'full') {
    $label_overrides = [
      'oe_reference_codes' => t('Identification'),
    ];

    if ($entity->get('oe_departments')->count() > 1) {
      $label_overrides['oe_departments'] = t('Related departments');
    }

    if ($entity->get('oe_publication_countries')->count() > 1) {
      $label_overrides['oe_publication_countries'] = t('Countries');
    }

    foreach ($label_overrides as $name => $label_override) {
      if (!$entity->get($name)->isEmpty() && isset($build[$name]['#title'])) {
        $build[$name]['#title'] = $label_override;
      }
    }

    // Change the 'Files' field group label to 'Documents' when a publication
    // collection is rendered.
    if ($entity->get('oe_publication_publications')->count() > 0) {
      $build['#fieldgroups']['group_item_files']->label = t('Documents');
    }
  }
}
