<?php

/**
 * @file
 * Module file used for theming the Publication content type.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\oe_theme_helper\ContentUtility;

/**
 * Implements hook_theme().
 */
function oe_theme_content_publication_theme() {
  return [
    'oe_theme_content_publication_description' => [
      'variables' => [
        'body' => '',
        'image' => '',
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_node() for the Publication node type.
 */
function oe_theme_content_publication_preprocess_node__oe_publication__teaser(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  // Add publication types to teaser metadata.
  if (!$node->get('oe_publication_type')->isEmpty()) {
    $variables['metas']['types'] = ContentUtility::getCommaSeparatedReferencedEntityLabels($node->get('oe_publication_type'));
  }

  // Add publication date to teaser metadata.
  $timestamp = $node->get('oe_publication_date')->date->getTimestamp();
  $variables['metas']['date'] = \Drupal::service('date.formatter')->format($timestamp, 'oe_theme_publication_date');

  // Add authors to teaser metadata.
  if (!$node->get('oe_author')->isEmpty()) {
    $variables['metas']['authors'] = ContentUtility::getCommaSeparatedReferencedEntityLabels($node->get('oe_author'));
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_publication_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Run only for "Publication" content type.
  if ($entity->bundle() !== 'oe_publication') {
    return;
  }

  // Override field labels.
  if ($build['#view_mode'] === 'full') {
    $label_overrides = [
      'oe_reference_codes' => t('Identification'),
    ];

    if ($entity->get('oe_departments')->count() > 1) {
      $label_overrides['oe_departments'] = t('Related departments');
    }

    if ($entity->get('oe_publication_countries')->count() > 1) {
      $label_overrides['oe_publication_countries'] = t('Countries');
    }

    foreach ($label_overrides as $name => $label_override) {
      if (!$entity->get($name)->isEmpty() && isset($build[$name]['#title'])) {
        $build[$name]['#title'] = $label_override;
      }
    }
  }
}
