<?php

/**
 * @file
 * Module file used for theming the Contact entity.
 */

declare(strict_types = 1);

use Drupal\oe_content_entity_contact\Entity\ContactInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_entity_contact_oe_contact_view_alter(array &$build, ContactInterface $entity, EntityViewDisplayInterface $display) {
  // Field labels are different in frontend and backend.
  // Here we override them, per view mode.
  $label_overrides = [
    'oe_address' => t('Postal address'),
    'oe_social_media' => t('Social media'),
  ];
  _oe_theme_helper_field_view_label_override($build, $entity, $label_overrides, ['full']);
}
