<?php

/**
 * @file
 * Module file used for theming the Contact entity.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\oe_content_entity_contact\Entity\ContactInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_entity_contact_oe_contact_view_alter(array &$build, ContactInterface $entity, EntityViewDisplayInterface $display) {
  // Field labels are different in frontend and backend.
  // Here we override them, per view mode.
  if ($build['#view_mode'] === 'full') {
    $label_overrides = [
      'oe_address' => t('Postal address'),
      'oe_social_media' => t('Social media'),
    ];

    foreach ($label_overrides as $name => $label_override) {
      if ($entity->hasField($name) && !$entity->get($name)->isEmpty() && isset($build[$name]['#title'])) {
        $build[$name]['#title'] = $label_override;
      }
    }
  }
}
