<?php

/**
 * @file
 * Module file.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_theme_demo_theme() {
  return \Drupal::service('plugin.manager.oe_theme_demo.demo_blocks')->hookTheme();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_theme_demo_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#base_plugin_id']) && $variables['elements']['#base_plugin_id'] === 'oe_theme_demo_block') {
    $suggestions[] = 'block__bare';
  }
}
