<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function oe_theme_demo_theme() {
  return \Drupal::service('plugin.manager.oe_theme_demo.demo_blocks')->hookTheme();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_theme_demo_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#base_plugin_id']) && $variables['elements']['#base_plugin_id'] === 'oe_theme_demo_block') {
    $suggestions[] = 'block__bare';
  }
}

/**
 * Implements hook_styleguide_info_alter().
 */
function oe_theme_demo_styleguide_info_alter(array &$definitions) {
  // Remove default styleguides.
  $default_definitions = [
    'image_styleguide' => 'image_styleguide',
    'default_styleguide' => 'default_styleguide',
    'search_styleguide' => 'search_styleguide',
    'comment_styleguide' => 'comment_styleguide',
  ];
  $definitions = array_diff_key($definitions, $default_definitions);
}
