<?php

/**
 * @file
 * Module file used for theming the Call for tenders content type.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\oe_content_call_tenders\CallForTendersNodeWrapper;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_call_tenders_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Run only for "Call for tenders" content type.
  if ($entity->bundle() !== 'oe_call_tenders') {
    return;
  }

  // Field labels are different in frontend and backend.
  // Here we override them, in full and teaser view mode.
  if (in_array($build['#view_mode'], ['full', 'teaser'])) {
    $label_overrides = [
      'body' => t('Description'),
      'oe_departments' => t('Departments'),
    ];

    if ($entity->get('oe_departments')->count() === 1) {
      $label_overrides['oe_departments'] = t('Department');
    }

    foreach ($label_overrides as $name => $label_override) {
      if (!$entity->get($name)->isEmpty() && isset($build[$name]['#title'])) {
        $build[$name]['#title'] = $label_override;
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_theme_content_call_tenders_preprocess_field__node__oe_call_tenders_deadline__full(&$variables, $hook) {
  _oe_theme_content_call_tenders_strike_deadline($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_theme_content_call_tenders_preprocess_field__node__oe_call_tenders_deadline__teaser(&$variables, $hook) {
  _oe_theme_content_call_tenders_strike_deadline($variables);
}

/**
 * Add strike through to deadline date when call for tenders is close.
 *
 * @param array $variables
 *   Element variables from preprocess.
 */
function _oe_theme_content_call_tenders_strike_deadline(array &$variables): void {
  $node = CallForTendersNodeWrapper::getInstance($variables['element']['#object']);
  if ($node->isClosed()) {
    // Cross out closed tender.
    $variables['attributes']['class'] = ['ecl-u-type-strike'];
  }
}

/**
 * Implements template_preprocess_node() for the CFT node type.
 */
function oe_theme_content_call_tenders_preprocess_node__oe_call_tenders__teaser(array &$variables): void {
  if (!isset($variables['elements']['extra_field_oe_call_tenders_label_status'])) {
    return;
  }
  $status = $variables['elements']['extra_field_oe_call_tenders_label_status'][0];
  $variant = _oe_theme_helper_prepare_status_variant($status['#name']);
  if (empty($variant)) {
    return;
  }
  $variables['badges'][] = [
    'label' => $status['#label']->render(),
    'variant' => $variant,
  ];
}
